api_version = "2026-04"

[[extensions]]
name = "Easy Internal Notes"
handle = "internal-notes-block"
type = "ui_extension"

  [[extensions.targeting]]
  target = "admin.product-details.secondary-vertical-stack.render"
  module = "./src/Block.tsx"

  [[extensions.targeting]]
  target = "admin.collection-details.secondary-vertical-stack.render"
  module = "./src/Block.tsx"
