api_version = "2026-04"

[[extensions]]
name = "Easy Internal Notes"
handle = "internal-notes-block"
type = "admin_block"

  [[extensions.targeting]]
  target = "admin.product-details.block.render"
  module = "./src/index.tsx"

  [[extensions.targeting]]
  target = "admin.collection-details.block.render"
  module = "./src/index.tsx"
